### ISSUE TITLE
diyca does not have proper support for SubjectAlternateNames (SAN) 

### ISSUE THREAD

**Issue by pekcheey** [texadactyl/diyca#12]
**Is your feature request related to a problem? Please describe.**
I cannot create an SSL cert via that can be used in chrome as it mandates the inclusion of SubjectAlternateName field.
I have tried to pass in a CSR that includes the SAN fields, but the resulting cert does not contain reference to the SubjectAlternateName in the request

**Describe the solution you'd like**
diyca should produce a cert that contains the SubjectAlternateName if it is in the request.

**Describe alternatives you've considered**
Safari still accepts the generated cert without the SubjectAlternateName but most of our resting is done with Chrome. 

**Additional context**
I'm using a Mac here.

**Comment by texadactyl** [comment]
I just now installed the diyca server on one of my Raspberry Pi boxes.  It could have been on an Intel/AMD system as long as it is running a Debian-flavor of Linux.  See docs/preparation_notes.txt.  Actually, it probably could run on a Mac server (E.g. minimac) with some changes to the preparation notes.

When I was done with installing the diyca server, I borrowed my spouse's Macbook Air.  I then installed the self-signed certificate of the diyca CA in the Keychain Access application and set the certificate to **Always Trust**.  Finally, I successfully browsed to the diyca server specifying https protocol in Chrome, Safari, and Firefox on the Mac.

Are you sure that you did that?  The Keychain Access application is very flexible.

Regarding the x.509 SubjectAlternateName field.  The CA's certificate does not carry it and you should not need it. The web server cerificate, of course, carries this field for authentication.  The value is the IP address of the machine where the diyca server is running.

**Comment by texadactyl** [comment]
If this was a production-grade Certificate Authority, there would be certainly be a SubjectAlternateName field in the CA's certificate that would be set to the DNS name of that particular CA (Calvin).  Also, the CA's cert would not be self-signed but instead signed by a well-known intermediate CA such as one from Verisign or Thawte.

The purpose of diyca is to facilitate realistic PKI cryptography based on X.509 certificates for application programs from day 1 of their development project.  Then, when system integration testing, user acceptance testing, and production certificates are available (staged), the applications have no source code to change; they have been performing PKI cryptography all along.

**Comment by pekcheey** [comment]
Oh. maybe I'm not using the package as you intended. 

Following the instructions on preparation docs/preparation_notes.txt 
I'm able to successfully browsed to the diyca server specifying https protocol in Chrome, Safari on the Mac as well.

On the diyca server page there is an option to upload a certificate signing request (CSR).
I tried uploading a CSR with a subject alternate name (SAN) and the program churned out a crt. 

I thought to use that crt as the ssl cert on a lighttp service I'm running on the raspberrypi.

I thought since I'd added Calvin as CA on my mac. 
And Calvin generated the crt, I should be able browse to the page with no problem.

Am I suppose to be able to do that?

**Comment by texadactyl** [comment]
See the example.users folder.  In there, you will find bob and alice, two communicating partners.  Both applications are written in Python.  If you follow the instructions in README.txt, you can run them such that they both have certificates signed by Calvin that are mutually acceptable (because they trust Calvin) and corresponding public/private key pairs.  This is the classical PKI with certificate application of peer-to-peer communications. I encourage you to try those applications.

When you added Calvin on your Mac to its certificate repository, you told the Mac to trust any web server certificate signed by Calvin.  Since the diyca web server certificate is signed by Calvin, your browsers are able to interact with the diyca server.

I am going to guess that the "lighttp service" is a minimized HTTP web server, capable of supporting HTTPS (TLS) since I see that it has a mod_ssl (similar to Apache).  If you want that server to be trusted by your Mac, then you must do exactly what this project does for the diyca server (see: ```diyca/bin/3.diyca_web_init.sh```):
1. Generate a CSR for the lighttp service.
2. Have Calvin sign it, producing a CRT file.
3. Store the CRT file in the lighttp service whever it stores the web server certificate (?).
4. Restart the lighttp service.

Once that is done, you will have implemented the usual 1-way authentication (host only) with a NEW web server.  In fact, now you have 2 web servers with server certificates signed by Calvin: diyca and your lighttp service.

**Comment by texadactyl** [comment]
It sounds like you are not interested in secure peer-to-peer communications (E.g. alice and bob) that contains _mutual_ authentication.  This is indeed the problem I was addressing with this project.  However, as you can see, Calvin can sign _any_ CSR so, yes, web servers can obtain certificates which are presentable to any client that trusts Calvin.

Note:

1. Outlined above is classic Internet authentication of the webserver; the client is not authenticated when the TLS session is set up.  
2. Presumably, there will be a subsequent user login similar to the diyca server.  That will ensure that the both parties are authenticated although in different ways.

**Comment by texadactyl** [comment]
One other point:  As stated in the front page of this project, it is not intended for PRODUCTION.  The diyca project is intended as a development/testing Certificate Authority (Calvin) to facilitate secure peer-to-peer communications right from the beginning of any development project.  It is assumed that eventually, the project will get proper certificates from a well-known authority (E.g. Thawte or Verisign) for use in production, maybe even before that in user acceptance testing ahead of time, depending on operational quality assurance requirements.

**Comment by texadactyl** [comment]
What problem are you actually trying to solve?
Why are you using the lighttp service?
What are your security requirements?

**Comment by pekcheey** [comment]
yup. I've tried the 4 steps you'd listed. And browsing via https (with the generated CRT) works with Safari and Firefox. 

But it does not work with Chrome and Vivaldi browser.
(Vivaldi being based off chromium that's probably why)

Because in addition to the cert being being certified by a CA. 
I suspect that chromium mandates that the SubjectAlternateName field must be set to the domain used to access the page.

All would be good if I am using Safari or Firefox. But I'm using Vivaldi and Chrome for my testing. And Chrome is the most popular browser after all. Hence the ticket.


# Background / Usecase

It's not real production. 
I'm running a private dokuwiki via lighhttp on a raspberrypi at home which I'm exposing to the internet on https. 

For SSL, I was previously using an old self-signed cert that expired back in 2015 so I was getting a ugly daily security exception nag by chrome. 

In addition to lighttp, I'm running couchdb on https (using the same cert) for use as a backend for https://noteself.org
as a shared clipboard across my devices.  And there's the ugly nag again before the connection can be established.  

At least the connections were secured.  Even thought the setup is still susceptible to a man-in-the-middle attack, I know, because it is not being verified by a trusted CA.  And I cannot trust the cert because it had expired. 

I was just too lazy to do anything about it until I chanced upon the following article
https://www.element14.com/community/community/raspberry-pi/blog/2017/12/10/do-it-yourself-certificate-authority-on-a-small-single-board-computer
and that's how I tried to setup diyca to see if I could get rid of the ugly prompts. And found that the generated crt doesn't contain the SAN that chromium need.

So then I've tried to generate a self signed cert with SAN. Added it to the trusted CA on my mac and android. And it's working now. i.e.  (no ugly prompt)

Security wise I should not be reusing the same ssl cert across lighttp and couchdb. 
But to manually managed self signed certs across the devices is too much of a hassle.
Ideally I would install / trust CAlvin once on each devices and that would allow for SSL on all my devices.

I understand that diyca is not meant for production.

But if diyca support SAN, it could be more useful to the multitude of raspberrypi owners out there with similar setup.

I'm not sure if mine is an intended usecase for diyca.
And I've no idea of the complexity involved in supporting SAN.
At your discretion, I can close the ticket.


----

> you want that server to be trusted by your Mac, then you must do exactly what
> this project does for the diyca server (see: diyca/bin/3.diyca_web_init.sh):

I see. I will give it a try.

**Comment by texadactyl** [comment]
My opinions:
- "exposing to the internet on https" = Production.
- "private dokuwiki via lighhttp on a raspberrypi at home which I'm exposing to the internet on https" is not private.

If some random person comes along and somehow connects to your web site, they will be given the ability to examine the invalid certificate signed by CA "Calvin".  I do not want "Calvin" to trace back to my project which was not intended to be used on the public Internet.

In file diyca/bin/diyca_calvin_cert.cfg, please change all of the following fields:
```
[default]
name                    = calvin

[ca_dn]
organizationName        = "DIYCA Org"
organizationalUnitName  = "DIYCA Staff"
commonName              = "Calvin"
```

Then, please restart installation.

Please do not use "Calvin" nor "DIYCA" on the public Internet.

Thank you.

**Comment by texadactyl** [comment]
Good write-up: https://www.techradar.com/news/software/how-ssl-and-tls-works-1047412

Again, browsers do not need your user CRT file created by the diyca server.  They need only to have access to Calvin's self-signed CRT file tagged as Always Trust (using the Keychain Access Mac application or in the browser's private repository - forgot which repository chromium & vivaldi use on a Mac).  The purpose of having the trusted CA's CRT information is to validate the web server's user CRT information during the TLS hand-shake.

So, the web server is the one that needs a user CRT file signed by a CA that the client (E.g. web browser) trusts.  Getting a client-side user CRT file signed by Calvin does nothing towards your goal; those are suitable for suitable for alice-bob (peer-to-peer) pre-communications TLS hand-shake.

On the public Internet, your Mac-based web browser accepts 1000s of web server CRT information in the TLS hand-shake because they are signed by a CA that the browser trusts (E.g. Verisign, Thawte).

I cannot explain the difference in your 3 browser behaviours as I am not there watching what's going on.  I believe what you are saying.  However, it may be that one or more of the Mac's browsers uses the keychain repository and one or more does not.  I know that sometime in the past, I had to place Calvin's CRT in one of the browser's repositiories in addition to the keychain repository.  But, I cannot remember which.

**Comment by texadactyl** [comment]
I think that I will have to make a special note for folks like you who intend to only use this for an Intranet web site as opposed to peer-to-peer mutual authentication.  In addition, I need to take "Calvin" and "DIY" out of Calvin's certificate configuration file.

Free advice: 
1. Test your web site with the Calvin CA within the privacy of your LAN.
2. Once you are satisfied that your web site and the various browser client entities are functioning correctly, please get a web server user certificate from a well-known CA for deploying on the public Internet.

**Comment by texadactyl** [comment]
I use vivaldi too.  Here is what I did to import Calvin's self-signed certificate on Linux (different process from Mac):
- In address bar: ```chrome://settings/certificates```
- Select tab Authorities
- Select import
- Select Calvin's certificate file
- In Certificate Authority pop-up: Trust this certificates for identifying websites
- Button OK
- Button Done

After that, my browser accepts any web server's user certificate that was signed by Calvin.

**Comment by texadactyl** [comment]
On my spouse's Mac (diyca version 2.1):
![20200809_132032.jpg](https://user-images.githubusercontent.com/11318756/89739080-3aa86580-da43-11ea-8cf8-34fe832b825c.jpg)

**Comment by texadactyl** [comment]
The SAN field is always generated for the user certificate.  E.g. diyca web server.  It will be also be generated for your lighttp server.

It is deliberately missing for Calvin's self-signed CA certificate.  Calvin is a testing CA whose certificate should be imported by the keychain app (on Mac) or the browser itself (on Linux) and marked as Always Trusted.  

A pay-for-use CA whose certificate is signed by a higher authority has a SAN field present.  Importing that CA certificate is not required normally since the certificate chain can be chased and verified during TLS hand-shake.

So, the title of this issue is, unfortunately, misleading.  However, I do not mind helping you to a solution.

**Comment by texadactyl** [comment]
@pekcheey 
Any updates?  No longer interested?
