### ISSUE TITLE
X509v3 Subject Alternative Names

### ISSUE THREAD

**Issue by bp529** [texadactyl/diyca#4]
Richard thank you for publishing your cert signer, it has helped me learn quite a bit about CAs. 

I wanted to ask if it supports specifying an Alternative Name via IP. I have successfully loaded the cert and it shows as valid when connecting to the device via hostname i.e. https://hostname.local, but if I access via the specified IP the certificate is shown to be invalid.

**Comment by texadactyl** [comment]
Currently, specifying an Alternative Name via IP is the only thing that works for the web server certificate - please see preparation notes.  So, yes it works.  

For example, my copy of diyca is running on a Raspberry Pi in my LAN at 192.168.1.104, port 8088:  So, I connect with the following URL:
```
https://192.168.1.104:8088/
```

Using a hostname like you have indicated should be rejected and you should see the following message in the Firefox version 58:
```
Your connection is not secure
The owner of HOSTNAME has configured their website improperly. 
To protect your information from being stolen, Firefox has not connected to this website.
```

Did you want the ability to connect by hostname as well as IP address?  I don't really want to get into the DNS business which requires a registered DNS name to resolve to the actual IP address (verified during SSL/TLS hand-shake).  Yes, one could build a local DNS server and make it work but that seems like overkill for the purpose of the diyca concept.

Have you tried setting the CN=hostname and the Alt name = IP address?

Your take?

**Comment by bp529** [comment]
Primarily, I would prefer to just use the IP. I thought the hostname was a requirement for the CN. Do you need to include the port number when specifying an Alternate Name via IP or can I just specify the IP in the CN field? If I can just specify the IP in the CN field, could you share the correct format using your diyca as an example? 

I posted my CSR below. 


`Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=ruckus.local, O=Home, L=SanDiego, ST=California, C=US
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:a8:d0:6d:b7:e5:bc:bf:a2:d8:e9:be:4c:4e:17:
                    e7:67:2c:94:33:c3:27:fe:c0:57:1f:ec:ab:71:e3:
                    2f:7c:0a:21:71:64:89:ea:fa:8c:84:3b:f2:46:b7:
                    07:b3:1c:0e:7f:b8:af:42:24:bf:2f:35:06:36:a7:
                    5b:ee:d7:bb:c6:f1:d9:29:3c:e5:b1:b4:1a:19:ad:
                    44:3c:33:2d:96:e2:95:9f:d0:90:2c:cf:59:4c:5f:
                    71:d6:99:c7:84:e7:7f:6a:7a:0b:9c:b7:e8:7f:cd:
                    86:8e:9a:29:03:1f:23:a1:f2:72:5d:93:61:70:a9:
                    6e:7e:f4:ce:15:55:c0:a0:0f:ce:23:44:9f:8e:e5:
                    fd:96:bf:bd:57:d3:0e:e6:24:81:c4:48:97:53:31:
                    a7:9f:ee:f6:a3:46:cc:c9:08:e5:8a:b5:b3:f3:0d:
                    85:f9:6d:e5:ee:90:b3:bb:18:8b:e2:8d:a3:90:99:
                    52:03:63:a6:f9:61:10:4b:a0:52:3e:f0:6a:9e:01:
                    59:b0:e8:bc:1d:89:00:46:f4:cb:0e:14:fc:45:a3:
                    95:b2:be:d2:6e:ab:71:e8:35:33:10:39:36:0f:74:
                    c4:f6:30:a7:63:30:02:8c:0b:02:bd:d7:fc:aa:c3:
                    a4:a8:64:4e:b6:8f:d1:ae:5f:47:30:0e:02:86:1d:
                    5b:99
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                IP Address:192.168.21.9
    Signature Algorithm: sha1WithRSAEncryption
        31:3d:aa:1a:ae:f2:a1:5b:ca:84:05:6d:fd:22:57:d1:36:c1:
        3a:8f:5c:0d:31:d2:26:2c:90:c6:e9:30:f1:4e:2e:a2:10:e9:
        78:c0:2b:9f:c2:86:34:68:e6:29:45:2b:5f:9f:b8:3b:39:8e:
        43:74:5f:49:dd:96:21:56:26:08:1e:10:da:ce:38:c1:36:5f:
        83:4c:22:43:91:04:95:5a:9c:1c:a4:b3:4d:af:e2:2f:71:03:
        ad:39:86:5b:b9:2d:7d:27:7c:af:bc:bd:b9:0e:f2:0a:ca:4e:
        a8:c4:51:59:29:27:6c:5b:9c:7c:0f:0a:d1:07:7e:91:cf:e7:
        6d:ca:d2:48:9a:8b:1b:5e:74:c5:c0:83:09:78:ba:94:c5:9f:
        af:72:9e:3f:0f:1a:69:64:5d:d5:13:f6:3d:73:ef:ad:04:26:
        b5:85:32:65:60:7d:80:f5:97:f1:9c:d0:ca:4d:ff:03:2c:83:
        87:85:6b:2f:e1:2a:87:04:0e:61:22:ea:fe:96:b0:44:1b:46:
        da:b5:7a:85:a0:41:71:41:23:4e:b5:51:a3:30:db:a1:a4:e4:
        0d:c1:ce:77:f9:b4:3f:31:2c:94:7f:ee:5a:c8:93:64:fd:4e:
        11:ee:13:73:b6:7b:08:c3:30:78:de:8e:ab:f1:5b:dd:4f:e8:
        cf:b7:95:ee`

**Comment by texadactyl** [comment]
In the future, I suggest that when providing a CSR, supply it as-is i.e. in its base64-encoded form which is the actual file contents.  Then, the receiver can save it as such and it will be automatically recognised as such on the receiver's file system.

Anyways, the above CSR looks like it will result in a correct CRT with Subject Alternative Name: IP Address:192.168.21.9.  Subsequently, if the web server is running at 192.168.21.9, Firefox, Safari, and MSIE should work fine as long as you have imported Calvin's CA CRT into the browser as a trusted authority.  Is this what you are experiencing?  

Do not try this project with Chrome!  Chrome, in the last few months, is having trouble with CAs who have signed user CSRs with a self-signed certificate.  I was surprised by this too very recently.  I will update README.md with a warning.

As I said before, the preparation notes explain the following:
- The port number is not part of the CSR; it goes in the web server's configuration file.
- In the [ext] section, subjectAltName = IP address where the web server will run.
- The [dn] section is just commentary because I didn't want to get in the DNS business for this isolated usage of certificates.  Yes, a production-grade CA will require knowing the actual domain name where the application is running but that is beyond the scope of this project - see README.md.

Note also that setting the [dn] cn field to the host name will not work.  It looks like you tried.  I tried using a host name and it does not work (as I expected).  The Common Name field is supposed to be a fully qualified domain name of the web server as stored on the DNS in use, hence, my use of subjectAltName as a bypass.

So, you must use IP address alone for this project.  When/if you move on to a real CA, your certificate-based applications will not change at all; the new certificate will, of course, be different but that is the only aspect of your application that will change.  Again, my motivation was to get developers to use certificates immediately rather than try to cram that in at the last second down the road which often leads to a myriad of unpleasant surprises.

Please let me know how you are doing.  Best wishes.

**Comment by texadactyl** [comment]
I just saw this DNS simulation inside the OpenSSL config file:
https://stackoverflow.com/questions/46152891/chrome-not-trust-https-and-show-err-ssl-server-cert-bad-format

See Answer 1:
```
CN=x

[alt_names]
DNS.1=x
```
x = html_12 in the code segment.

I'll give it a try later on.  Why don't you?

**Comment by texadactyl** [comment]
I think that I found the problem associated with Chrome version 64.  The web server certificate version generated by diyca's use of openssl is 1 but the certificate contain version 3 extensions.  Firefox, MSIE, Safari, and earlier versions of Chrome are forgiving; Chrome 64 is not.  

In any case, this is my mistake.  I will track this as a separate issue which needs some new code.


Update: This new issue (#5) was just fixed and closed.  You could actually repeat fix by making the following change in your local copy of bin/3.diyca_web_init.sh:
```
# Added parameters -extfile and -extensions:
openssl ca -batch \
   -cert $CA_CERT_FILE \
   -config $CA_CERT_CONFIG \
   -keyfile $CA_KEY_NAME \
   -extfile $USER_CERT_CONFIG \
   -extensions ext \
   -in $USER_CSR \
   -out $USER_OUT_CRT
```
